name: Lint

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort flake8 mypy

    - name: Check formatting with black
      run: |
        black --check dictlens/ tests/

    - name: Check import sorting with isort
      run: |
        isort --check-only --profile black dictlens/ tests/

    - name: Lint with flake8
      run: |
        flake8 dictlens/ tests/ --max-line-length=100 --extend-ignore=E203,W503

    - name: Type check with mypy
      run: |
        mypy dictlens/ --ignore-missing-imports
